enable debug
Signed-off-by: Bruno Vavala <bruno.vavala@intel.com>

diff --git a/common/crypto/Makefile b/common/crypto/Makefile
--- a/common/crypto/Makefile
+++ b/common/crypto/Makefile
@@ -8,6 +8,9 @@ include $(TOP)/build.mk
 BUILD_DIR := _build
 
 export PDO_DEBUG_BUILD=1
+export FPC_GDB_DEBUG_ENABLED=1
+
+
 PDO_ENCLAVE_CODE_SIGN_PEM := "pdo_enclave_code_sign.pem"
 
 $(BUILD_DIR):
@@ -25,7 +28,7 @@ build: $(BUILD_DIR)
 test: build
 	env CTEST_OUTPUT_ON_FAILURE=1 \
 	$(MAKE) -C $(BUILD_DIR) test || \
-		(echo "PDO crypto tests failed. Define PDO_DEBUG_BUILD=1 environment for enabling logging in tests." && cat _build/Testing/Temporary/*.log && exit 1)
+		(echo "PDO crypto tests failed. Define PDO_DEBUG_BUILD=1 environment for enabling logging in tests." && cat _build/Testing/Temporary/*.log && cd _build/tests && ls && sgx-gdb -ex run ./get_attestation_app && exit 1)
 
 clean:
 	-if [ -d $(BUILD_DIR) ];then $(MAKE) -C $(BUILD_DIR) clean; fi
